Remove coreboot detection, add skip_grub={0,1}
QubesOS/qubes-installer-qubes-os pull request #13
Opened 2017-04-26 15:12 UTC by rustybird

Successfully tested the following scenarios with the R3.2 iso:

- `skip_grub=1`, following instructions from https://github.com/QubesOS/qubes-issues/issues/2118#issue-162353768
- No `skip_grub` parameter, default installation layout
- No `skip_grub` parameter, btrfs installation layout (generated by Anaconda)

The dmidecode package could be removed now, but they still seem like useful tools to have for debugging installer problems.

2017-04-27 22:19 UTC, marmarek requested changes

2017-04-27 22:19 UTC, marmarek commented on anaconda/pyanaconda/bootloader.py
> +        self.skip_bootloader = bool(int(flags.cmdline.get("skip_grub") or "0"))
Better use `flags.cmdline.getbool("skip_grub", False)`

2017-05-01 12:20 UTC, rustybird commented
Fixed. Booting with/without `skip_params` assigns the expected values to `self.skip_bootloader`.

2017-05-05 19:30 UTC, marmarek approved these changes

2017-05-05 19:32 UTC, merged