Mock
QubesOS/qubes-installer-qubes-os pull request #22
Opened 2018-05-09 16:02 UTC by fepitre

2018-05-09 18:31 UTC, marmarek commented on blivet/python-blivet.spec
> +Source0: %{realname}-%{realversion}.tar.gz
I'd leave URL here. If nothing more, as an info how to get new upstream version (`spectool --get-files` do that). You already have `(notdir ...)` in `SOURCE_ARCHIVE_NAME`, so it should just work, no?

2018-05-09 22:02 UTC, fepitre commented
Following your comment, I kept the URL. I did it in two times initially, used notdir and then removed the URL but of course, it works well with the URL.

2018-05-13 22:30 UTC, marmarek requested changes

2018-05-13 22:30 UTC, marmarek commented on pungi/pungi.spec
> +Source0:        %{name}-%{version}.tar.bz2
URL here too.

2018-05-14 10:36 UTC, fepitre commented on pungi/pungi.spec
> +Source0:        %{name}-%{version}.tar.bz2
Done.

2018-05-14 23:59 UTC, marmarek commented
It can't find pykickstart-2.32.tar.gz while building src.rpm - it's looking for it in the wrong directory. Build log: https://gist.github.com/marmarek/a8c0b08e76f23bcefc9513f9aaf2178a

2018-05-15 13:51 UTC, marmarek commented
I had outdated builder and builder-rpm, with new one it works.

2018-05-15 13:51 UTC, marmarek approved these changes

2018-05-15 13:52 UTC, merged