Fc32
QubesOS/qubes-installer-qubes-os pull request #37
Opened 2020-04-08 13:50 UTC by fepitre

2020-05-27 02:37 UTC, marmarek requested changes

2020-05-27 02:37 UTC, marmarek commented on .travis.yml
> - - ~/qubes-builder/scripts/travis-build
A side effect of travis-build script was copying (actually - hardlinking) installer-qubes-os into ~/qubes-builder. See travis failure now.

2020-05-27 15:42 UTC, marmarek commented
Travis build still fails. In a different way (losetup failed).

2020-06-02 23:23 UTC, JarrahG commented
Not sure whether this is fixed elsewhere, but building the ISO fails with self.groups["qubes-ui"] not being defined. 
```python
-> Building installer-qubes-os iso for fc32 (logfile: build-logs/installer-qubes-os-iso-fc32.log)...
--> build failed!
    main(ns, persistdir, cachedir)
  File "/usr/lib/python3.8/site-packages/pungi/scripts/pungi_gather.py", line 163, in main
    packages, conditional_packages = ksparser.get_packages(dnf_obj)
  File "/usr/lib/python3.8/site-packages/pungi/ks.py", line 160, in get_packages
    ) = dnf_obj.comps_wrapper.get_packages_from_group(
  File "/usr/lib/python3.8/site-packages/pungi/dnf_wrapper.py", line 97, in get_packages_from_group
    group = self.groups[group_id]
KeyError: 'qubes-ui'
make[1]: *** [Makefile:87: iso-installer-gather] Error 1
```

2020-06-03 00:10 UTC, marmarek commented
> but building the ISO fails with self.groups["qubes-ui"] not being defined.

This looks like submodules not updated. Call `git submodule update --init` in installer-qubes-os dir.

2020-06-03 07:14 UTC, fepitre commented
> git submodule update --init

It does not change anything.

2020-06-13 14:36 UTC, merged